# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    versioning-strategy: "increase"
    groups:
      semantic-release-ecosystem:
        patterns:
          - "semantic-release"
          - "@semantic-release/*"
          - "@types/semantic-release*"
      commitlint-ecosystem:
        patterns:
          - "@commitlint/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
