name: Release

on:
  push:
    branches:
      - main

jobs:
    publish:
      runs-on: ubuntu-latest
      permissions: write-all
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: yarn
            registry-url: "https://registry.npmjs.org"
        - run: yarn install --frozen-lockfile
        - name: Semantic release
          uses: cycjimmy/semantic-release-action@v4.1.0
